[package]
name = "debugless-unwrap"
version = "1.0.0"
authors = ["Tamme Schichler <tamme@schichler.de>"]
rust-version = "1.56"
edition = "2021"
description = "Unwrap Result<!Debug, !Debug> and Option<!Debug>"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Tamschi/debugless-unwrap"
keywords = ["unwrap", "debug", "no-debug", "option", "result"]
categories = ["rust-patterns"]
readme = "README.md"
include = [
	"**/*.rs",
	"Cargo.toml",
	"CHANGELOG.md",
	"CODE_OF_CONDUCT.md",
	"LICENSE-*",
	"README.md",
]

[badges]
is-it-maintained-issue-resolution = { repository = "Tamschi/debugless-unwrap" }
is-it-maintained-open-issues = { repository = "Tamschi/debugless-unwrap" }
maintenance = { status = "experimental" }

[dev-dependencies]
assert-panic = "1.0.1"
