[package]
name = "debugless-unwrap"
version = "0.0.1"
authors = ["Tamme Schichler <tamme@schichler.dev>"]
edition = "2018"
description = "Unwrap Result<!Debug, !Debug> and Option<!Debug>"
license = "MPL-2.0"
repository = "https://github.com/Tamschi/debugless-unwrap"
include = [
	"**/*.rs",
	"Cargo.toml",
]
publish = false
