# Largely inspired by https://github.com/dtolnay/syn/blob/master/.github/workflows/ci.yml under MIT OR Apache-2.0.
name: CI
on:
  pull_request:
  push:
  schedule: [cron: "0 8 * * 5"] # 8:00 on Fridays

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@1.70
    - run: cat CI.toml >> Cargo.toml
    - run: cargo test --workspace --all-features

  check:
    name: Check on Rust ${{matrix.rust}}${{format(' ({0})', matrix.os)}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      matrix:
        os: [macos, ubuntu, windows]
        rust: [1.56.0, stable, beta]
        include:
        - os: ubuntu
          no-workspace: --lib
    env:
      workspace: ${{matrix.no-workspace || '--workspace'}}
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@1.70
    - run: cat CI.toml >> Cargo.toml
    - run: cargo +${{matrix.rust}} check ${{env.workspace}} --no-default-features
    - run: cargo +${{matrix.rust}} check ${{env.workspace}}
    - run: cargo +${{matrix.rust}} check ${{env.workspace}} --all-features

  minimal-versions:
    name: Minimal Versions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@1.70
    - run: cat CI.toml >> Cargo.toml
    - run: cargo +nightly update -Z minimal-versions
    - run: cargo +nightly check --lib --all-features

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@1.70
      with:
        components: clippy
    - run: cat CI.toml >> Cargo.toml
    - run: cargo clippy --workspace --all-features

  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@1.70
      with:
        components: rustfmt
    - run: cat CI.toml >> Cargo.toml
    - run: cargo fmt --all -- --check
